/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MAdmissionRouteImport } from './routes/m.admission'
import { Route as MSlugRouteImport } from './routes/m.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MAdmissionRoute = MAdmissionRouteImport.update({
  id: '/m/admission',
  path: '/m/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m/$slug': typeof MSlugRoute
  '/m/admission': typeof MAdmissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/m/$slug': typeof MSlugRoute
  '/m/admission': typeof MAdmissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m/$slug': typeof MSlugRoute
  '/m/admission': typeof MAdmissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/m/$slug' | '/m/admission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/m/$slug' | '/m/admission'
  id: '__root__' | '/' | '/m/$slug' | '/m/admission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MSlugRoute: typeof MSlugRoute
  MAdmissionRoute: typeof MAdmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/admission': {
      id: '/m/admission'
      path: '/m/admission'
      fullPath: '/m/admission'
      preLoaderRoute: typeof MAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MSlugRoute: MSlugRoute,
  MAdmissionRoute: MAdmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
